FROM ubuntu:latest

ENV DEBIAN_FRONTEND=noninteractive

RUN apt update && apt install -y \
    python3 \
    python3-poetry \
    python3-pip \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY pyproject.toml poetry.lock ./

RUN poetry install
COPY . .
RUN poetry install

EXPOSE 5001

CMD poetry run dev & \
    npm run tailwind-dev & \
    wait
