services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5001:5001"
      - "5678:5678"
    volumes:
      - ./app:/app/app:rw
    env_file:
      - .env
    environment:
      - ENV=dev
